### ISSUE TITLE
a dumb question.

### ISSUE THREAD

**Issue by mujaffasBMW** [zokrtes/Mujaffas-BMW-3D#1]
how do you start the game?

**Comment by zokrtes** [comment]
@mujaffasBMW  This game is yet to be released, for now the project files are open-source and this is what you've downloaded. If you want to test the "game" (which there really isn't much of), you would have to download the game engine Godot 3.4 and open  the project files you downloaded.
- https://godotengine.org/download
- https://godotengine.org/qa/53461/how-to-import-a-folder-containing-a-godot-project
